ECB/ECB/Models/DatabaseContext.cs
using Microsoft.EntityFrameworkCore;

namespace ECB.Models
{
    public class DatabaseContext: DbContext
    {
        public DatabaseContext(DbContextOptions<DatabaseContext> options):base(options)
        {

        }
        public DbSet<Food> Foods { get; set; }
    }
}

ECB/ECB/Models/ErrorViewModel.cs
namespace ECB.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ECB/ECB/Models/Food.cs
using System.ComponentModel.DataAnnotations;

namespace ECB.Models
{
    public class Food
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        [DataType(DataType.Text)]
        public string Description { get; set; }


    }
}

ECB/ECB/Controllers/AuthController.cs
using Microsoft.AspNetCore.Mvc;

namespace ECB.Controllers
{
    public class AuthController : Controller
    {
        public IActionResult Signup()
        {
            return View();
        }
        public IActionResult Login()
        {
            return View();
        }
    }
}

ECB/ECB/Controllers/FoodsController.cs
using Microsoft.AspNetCore.Mvc;
using ECB.Models;
namespace ECB.Controllers
{
    public class FoodsController : Controller
    {
        public DatabaseContext _context;

        public FoodsController(DatabaseContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var food = _context.Foods.ToList();//select * from <table_name>
            return View(food);
        }

        public IActionResult Create()
        {
            return View();
        }
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Food fs)
        {
            if (ModelState.IsValid)
            {
                var e = new Food()
                {
                    Name = fs.Name,
                    Description = fs.Description
                };
                _context.Foods.Add(e);
                _context.SaveChanges();
                TempData["msg"] = "Saved Succesfully";
                return RedirectToAction("Index");
            }
            else
            {
                TempData["error"] = "Some error ocured";
                return View();
            }
        }
        public IActionResult Remove(int id)
        {
            var em = _context.Foods.SingleOrDefault(f => f.Id == id);//select * from foods where id=f 
            _context.Foods.Remove(em);
            _context.SaveChanges();
            TempData["msg"] = "Succesfully Deleted";
            return RedirectToAction("Index");
        }
        public IActionResult Edit(int id)
        {  
            var em = _context.Foods.SingleOrDefault(f => f.Id == id);
            return View(em);
        }
        [HttpPost]
        public IActionResult Edit(Food f)
        {
            if (ModelState.IsValid)
            {
                _context.Foods.Update(f);
                _context.SaveChanges();
                TempData["msg"] = "Updated Succesfully";
                return RedirectToAction("Index");
            }
            else
            {
                TempData["msg"] = "Error Occured";
                return View();
            }
        }
    }
}

ECB/ECB/Controllers/HomeController.cs
using ECB.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ECB.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ECB/ECB/Views/Food/Create.cshtml
@{
    ViewData["Title"] = "Create Food";
}
@model ECB.Models.Food

<div class="row jusity-content-md-center">
    <div class="col-8">
        <h4 class="text-danger">Create Recipe</h4>
        <hr/>
        @if (TempData["msg"] is not null)
        {
            <div class="alert alert-success">@TempData["msg"]</div>
        }
          @if (TempData["error"] is not null)
        {
            <div class="alert alert-danger">@TempData["error"]</div>
        }
        <form method="post" asp-controller="Recipe" asp-action="Create">
            <div class="mb-3">
                <label asp-for="Name" class="form-label"></label>
                <input asp-for="Name" class="form-control" />
                <span class="text-danger" asp-validation-for="Name"></span>
            </div>

             <div class="mb-3">
                <label asp-for="Description" class="form-label"></label>
                <textarea asp-for="Description" class="form-control"> </textarea>
                <span class="text-danger" asp-validation-for="Description" rows="3" placeholder="Say something about the dish"></span>
            </div>
            <hr/>
            <button type="submit" class="btn btn-success">Save</button>
        </form>
    </div>
</div>

ECB/ECB/Views/Foods/Create.cshtml
@model ECB.Models.Food

@{
    ViewData["Title"] = "Create";
}

<h1>Add Dish</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        @if(TempData["msg"] is not null)
        {
            <div class="alert alert-success">@TempData["msg"]</div>
        }
        @if(TempData["error"] is not null)
        {
            <div class="alert alert-danger">@TempData["error"]</div>
        }
        <form method="post" asp-action="Create" asp-controller="foods">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label" placeholer= "Eg: Mo:Mo"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div><br />
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"> </textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div><br />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ECB/ECB/Views/Foods/Delete.cshtml
@model ECB.Models.Food

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Food</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ECB/ECB/Views/Foods/Details.cshtml
@model ECB.Models.Food

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Dish</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ECB/ECB/Views/Foods/Edit.cshtml
@model ECB.Models.Food

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit Dish</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        @if(TempData["msg"] is not null)
        {
            <div class="alert alert-success">@TempData["msg"]</div>
        }
        @if(TempData["error"] is not null)
        {
            <div class="alert alert-danger">@TempData["error"]</div>
        }
        <form method="post" asp-action="Edit" asp-controller="foods">
            <input type="hidden" asp-for="Id" />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label" placeholer= "Eg: Mo:Mo"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div><br />
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"> </textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div><br />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ECB/ECB/Views/Foods/Index.cshtml
@model IEnumerable<ECB.Models.Food>

@{
    ViewData["Title"] = "All Food";
}

<h1>Dish List</h1>
<hr />
@if(TempData["msg"] is not null)
{
    <div class="alert alert-success">@TempData["msg"]</div>
}
@if(TempData["error"] is not null)
{
    <div class="alert alert-danger">@TempData["error"]</div>
}
<div class="row justify-content-md-center">
    <table class="table table-border">
        <thead>
            <th>Name</th>
            <th>Description/Recipe</th>
            <th>Action</th>
        </thead>
        <tbody>
            @foreach(var e in Model)
            {
                <tr class="text-lg-start">
                    <td>@e.Name</td>
                    <td>@e.Description</td>
                    <td>
                        <a class="btn btn-primary" asp-controller="foods" asp-action="Edit" asp-route-id="@e.Id">Edit</a>
                        <a class="btn btn-danger" asp-controller="foods" asp-action="Remove" asp-route-id="@e.Id">Delete</a>
                    </td>
                </tr>
            }
       </tbody>
    </table>
   
</div>
<a class="btn btn-success" asp-action="Create" asp-controller="Foods">Click here to add a new dish</a>

<div>
    <br />
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ECB/ECB/Views/Foods/Signup.cshtml
@{
    ViewData["Title"] = "Signup";
}
<div class="row justify-content-md-center">
    <div class="col-6">
        <div class="card">
            <div class="card-body">
                <h3>Signup</h3>
                <form method="post">
                    <div class="mb-3">
                        <label for="exampleFormControlInput1" class="form-label">Email address</label>
                        <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
                    </div>
                    <div class="mb-3">
                        <label for="fullname" class="form-label">Full Name</label>
                        <input type="text" class="form-control" id="fullname" placeholder="Shree Ghimire">
                    </div>
                    <div class="mb-3">
                        <label for="pass1" class="form-label">Password</label>
                        <input type="password" class="form-control" id="pass1">
                    </div>
                    <div class="mb-3">
                        <label for="pass2" class="form-label">Re-type Password</label>
                        <input type="password" class="form-control" id="pass2">
                    </div>
                    <hr />
                    <button type="submit" class="btn btn-success">Signup</button>
                </form>
            </div>
        </div>
    </div>
</div>

ECB/ECB/Views/Foods/login.cshtml
@{
    ViewData["Title"] = "Login";
}

<div class="row justify-content-md-center">
    <div class="col-6">
        <div class="card">
            <div class="card-body">
                <h3>Login</h3>
                <div class="mb-3">
                    <label for="exampleFormControlInput1" class="form-label">Email address</label>
                    <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
                </div>
                <div class="mb-3">
                    <label for="pass1" class="form-label">Password</label>
                    <input type="password" class="form-control" id="pass1">
                </div>
                <hr />
                <button type="submit" class="btn btn-success">Login</button>
            </div>
        </div>
    </div>
</div>

ECB/ECB/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<div class="image">
    <div class="text-center">
        <h1 class="display-4">Welcome to Cookbook</h1>
    </div>
    <div class="login">
        <div class="mb-3">
         <button type="submit" class="btn btn-success">
         <a class="nav-link text-light" asp-area="" asp-controller="foods" asp-action="Login">Login</a>
         </button>
        </div>
        <div class="mb-3">
         <button type="submit" class="btn btn-success">
             <a class="nav-link text-light" asp-area="" asp-controller="foods" asp-action="Signup">Signup</a></button>
        </div>
    </div>
</div>

ECB/ECB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ECB</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/Index.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ECB</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Foods" asp-action="Index">Dish List</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Foods" asp-action="Create">Add Dish</a>
                        </li>                      
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - E-Cookbook - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>